# pandas入门

* pandas 是基于NumPy 的一种工具，该工具是为解决数据分析任务而创建的。

* pandas最初被作为金融数据分析工具而开发出来，因此，pandas为时间序列分析提供了很好的支持。 

* Pandas的名称来自于面板数据（panel data）和python数据分析（data analysis）。

#### pandas vs NumPy

* pandas支持大部分NumPy风格的数组计算

* NumPy更适合处理同质型的的数值类数组数据,而pandas使用用来处理表格型或异质型数据

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
from pandas import Series, DataFrame

## 1. pandas数据结构介绍

* 为了入门pandas，需要熟悉两个常用的工具数据结构：Series和DataFrame。

###  （1）Series

* Series是一种一维的数组型对象，它包含了一个值序列（与NumPy中的类型相似），并且包含了数据标签，称为索引（index）。


* 最简单的序列可以仅仅由一个数组形成：

In [124]:
obj = pd.Series([4, 7, 'str1', 3])
obj

0       4
1       7
2    str1
3       3
dtype: object

In [33]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

* 交互式环境中Series的字符串表示，索引在左边，值在右边。

In [125]:
obj.values

array([4, 7, 'str1', 3], dtype=object)

In [126]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

* 通常需要创建一个索引序列，用标签标识每个数据点：

In [10]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [128]:
obj2.values

array([-5.3,  7.2,  3.6,  4.5,  nan])

In [127]:
obj2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

* 与NumPy的数组相比，可以在从数据中选择数据的时候使用标签来进行索引：

In [12]:
obj2['a']

-5

In [13]:
obj2['d'] = 6

In [14]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [130]:
obj2[2]

3.6

In [131]:
obj2[:2]

a   -5.3
b    7.2
dtype: float64

In [132]:
obj2[2:]

c    3.6
d    4.5
e    NaN
dtype: float64

* 使用NumPy的函数或NumPy风格的操作，比如使用布尔值数组进行过滤，与标量相乘，或是应用数学函数，这些操作将保存索引值连接：

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

* 从另一个角度考虑Series，可以认为它是一个长度固定且有序的字典，因为它将索引值和数据值按位置配对。

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

* 如果已经有数据包含在Python字典中，可以使用字典生成一个Series：

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

* 当把字典传递给Series构造函数时，产生的Series的索引将是排序好的字典键。

In [134]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

* pandas中使用 <b>isnull</b>和<b>notnull</b>函数来检查缺失数据：

In [135]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [136]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [137]:
obj4[pd.notnull(obj4)]

Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

* <b>isnull</b>和<b>notnull</b>也是Series的实例方法：

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [139]:
obj4[obj4.notnull()]

Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

* 对于很多应用来说，在数学操作中自动对齐索引是Series的一个非常有用的特性：

In [26]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

* Series对象自身和其索引都有name属性，这个特性与pandas其他重要功能集成在一起：

In [24]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

* Series的索引可以通过按位置赋值的方式进行改变：

In [25]:
obj
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### （2）DataFrame

* DataFrame表示的是矩阵的数据表，它包含已排序的列集合，每一列可以是不同的值类型（数值、字符串、布尔值等）。

In [29]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

* 产生的DataFrame会自动为Series分配索引，并且列会按照排序的顺序排列：

In [28]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

* 对于大型DataFrame，head方法将会只选出头部的五行：

In [29]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

* 如果指定了列的顺序，DataFrame的列将会按照指定顺序排列：

In [30]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

* 如果传的列不包含在字典中，将会在结果中出现缺失值：

In [141]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

year  state  pop  debt
one     NaN    NaN  NaN   NaN
two     NaN    NaN  NaN   NaN
three   NaN    NaN  NaN   NaN
four    NaN    NaN  NaN   NaN
five    NaN    NaN  NaN   NaN
six     NaN    NaN  NaN   NaN

In [142]:

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

* DataFrame中的一列，可以按字典型标记或属性那样检索为Series：

In [143]:
frame2['state']

one     NaN
two     NaN
three   NaN
four    NaN
five    NaN
six     NaN
Name: state, dtype: float64

In [144]:
frame2.year

one     NaN
two     NaN
three   NaN
four    NaN
five    NaN
six     NaN
Name: year, dtype: float64

* 注意，返回的Series与原DataFrame有相同的索引，且其name属性也会被合理地设置。

* 行也可以通过位置或特殊属性<b>loc</b>进行选取：

In [35]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

* 列的引用是可以修改的。例如，空的'debt'列可以赋值为标量值或值数组：

In [36]:
frame2['debt'] = 16.5
frame2
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

* 将列表或数组赋值给一个列时，值的长度必须和DataFrame的长度相匹配。

In [37]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

* 如果被赋值的列并不存在，则会生成一个新的列。<b>del</b>关键字可以像在字典中那样对DataFrame删除列。

* 在<b>del</b>的例子中，首先增加一列，这一列是布尔值，判断条件是state列是否为'Ohio'：

In [38]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

* <b>del</b>方法可以用于移除之前新建的列：

In [39]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

* 另一种常用的数据形式是包含字典的嵌套字典：

In [40]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

* 如果嵌套字典被赋值给DataFrame，pandas会将字典的键作为列，将内部字典的键作为行索引：

In [41]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

* 可以使用类似NumPy的语法对DataFrame进行转置操作（调换行和列）：

In [42]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

* 内部字典的键被联合、排序后形成了结果的索引。如果明确指定了索引，内部字典的键将不会被排序：

In [43]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

* 包含Series的字典也可以用于构造DataFrame：

In [44]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

* 如果设置了DataFrame的index和columns的name属性，则这些name属性也会被显示出来：

In [45]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

* 跟Series一样，DataFrame的values属性也会以二维ndarray的形式返回DataFrame中的数据：

In [46]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

* 如果DataFrame各列的数据类型不同，则values的dtype就会选用能兼容所有列的数据类型：

In [48]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)